apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: busybox
        spec:
          containers:
          - image: busybox
            name: busybox
            resources: {}
          restartPolicy: Always
  schedule: '* * * * *'
status: {}
